version: '2'
vars:
  BASIC_NETWORK: weather_app_network
tasks:
  copy-basic-files:
    desc: Create basic config files based on .dist
    cmds:
      - test -f .env || cp .env.dist .env
      - test -f docker-compose.yaml || cp docker-compose.yaml.dist docker-compose.yaml
  init:
    desc: Initialize application with docker
    cmds:
      - task: copy-basic-files
      - docker network create --driver=bridge {{.BASIC_NETWORK}} || true
      - docker-compose up -d --build
      - docker-compose run --rm php-fpm composer install
      - task: prepare-dev-db

  start:
    desc: Start application with docker
    cmds:
      - docker-compose up -d
      - docker-compose run --rm php-fpm composer install

  prepare-dev-db:
    desc: Prepare database structure
    cmds:
      - docker-compose run --rm php-fpm bin/console doctrine:database:drop --force --if-exists
      - docker-compose run --rm php-fpm bin/console doctrine:database:create
      - docker-compose run --rm php-fpm php bin/console doctrine:m:m --no-interaction
      - docker-compose run --rm php-fpm bin/console doctrine:schema:update --force
      - docker-compose run --rm php-fpm bin/console doctrine:fixtures:load
